version: "3.8"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=justin123
      - POSTGRES_DB=bookcart
    ports:
      - 5434:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
     - DATABASE_USERNAME=postgres
     - DATABASE_NAME=bookcart
     - DATABASE_HOST=postgres
     - DATABASE_PASSWORD=justin123
    depends_on:
      - postgres
    entrypoint: 
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: ["/app/main"]
volumes:
   db-data: 