version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=justin123
      - POSTGRES_DB=bookcart
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  api:
    build: 
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:justin123@postgres:5432/bookcart?sslmode=disable
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"  
      ]
    command: ["./app"]
volumes:
 postgres-data: