version: "3.8"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=justin123
      - DATABASE_NAME=bookcart
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5434:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - dbURL=postgres://postgres:justin123@postgres:5432/bookcart?sslmode=disable
    depends_on:
      - postgres
    entrypoint: 
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: ["/app/main"]
volumes:
   db-data: 